Examen

In [41]:
import numpy as np
from scipy import ndimage
from scipy import misc
import pandas as pd

2)

In [2]:
vector_de_ceros = np.zeros(10)

In [3]:
vector_de_ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3)

In [6]:
vector_de_ceros_dos = np.zeros(10)
vector_de_ceros_dos[4] = 1 
vector_de_ceros_dos

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

4)

In [9]:
vector_50_elementos = np.arange(50)
print(vector_50_elementos[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


5)

In [11]:
matriz_3x3 = np.random.randint(0,8, size=(3,3))
matriz_3x3

array([[1, 5, 7],
       [6, 3, 0],
       [7, 4, 1]])

6)

In [39]:
arreglo = [1,2,0,0,4,0]
no_ceros = np.where(arreglo != 0)
no_ceros

(array([0]),)

7)

In [15]:
matriz_identidad_3x3 = np.eye(3)
matriz_identidad_3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

8)

In [19]:
matriz3x3x3 = np.random.randint(1,10, size=(3,3,3))
matriz3x3x3

array([[[9, 9, 7],
        [9, 1, 7],
        [7, 9, 4]],

       [[3, 4, 9],
        [9, 2, 9],
        [6, 5, 3]],

       [[1, 9, 2],
        [2, 5, 2],
        [4, 1, 2]]])

9)

In [37]:
matriz_10x10 = np.random.rand(10, 10)
mayor = matriz_10x10.max()
minimo = matriz_10x10.min()
matriz_10x10
print('mayor', mayor)
print('menor', minimo)


mayor 0.9998715194322155
menor 0.021008278146097292


10)

In [42]:
mapache = misc.face()
color_1 = mapache.item(0,0,0)
color_2 = mapache.item(255,255,255)

IndexError: index 255 is out of bounds for axis 2 with size 3

11)

In [48]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

mylist_serie = pd.Series(mylist)
myarr_serie = pd.Series(myarr)
mydict = pd.Series(mydict)

mydict

a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64

12) Como convertir el indice de una serie en una columna de un DataFrame?

In [ ]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)


13) ¿Como combinar varias series para hacer un DataFrame?


In [49]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

df_datos = {"letras": ser1, "numeros": ser2} 
df_combinacion = pd.DataFrame(df_datos)
print(df_combinacion)

   letras  numeros
0       a        0
1       b        1
2       c        2
3       e        3
4       d        4
5       f        5
6       g        6
7       h        7
8       i        8
9       j        9
10      k       10
11      l       11
12      m       12
13      n       13
14      o       14
15      p       15
16      q       16
17      r       17
18      s       18
19      t       19
20      u       20
21      v       21
22      w       22
23      x       23
24      y       24
25      z       25


14) ¿Como obtener los items que esten en una serie A y no en una serie B?

In [96]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

items_A = ser1[~ser1.isin(ser2)]

print(f"items\n{items_A}")

items
0    1
1    2
2    3
dtype: int64


15) ¿Como obtener los items que no son comunes en una serie A y serie B?

In [98]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

items_A = ser1[~ser1.isin(ser2)]
items_B = ser2[~ser2.isin(ser1)]
items_no_comunes = pd.concat([items_A, items_B])

print(f"no comunes\n{items_no_comunes}")

no comunes
0    1
1    2
2    3
2    6
3    7
4    8
dtype: int64


16) ¿Como obtener el numero de veces que se repite un valor en una serie?

In [58]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
print(ser)

0     e
1     a
2     g
3     a
4     d
5     h
6     d
7     c
8     g
9     a
10    f
11    f
12    e
13    c
14    g
15    h
16    h
17    a
18    b
19    b
20    a
21    e
22    d
23    g
24    b
25    e
26    e
27    h
28    b
29    h
dtype: object


17) ¿Como mantener los 2 valores mas repetidos de una serie, y a los demas valores cambiarles por 0 ?

In [107]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

valor_unicos = ser.unique()
valor_unicos


array([2, 3, 1, 4])

In [77]:
ser = pd.Series(np.random.randint(1, 10, 35))
#shape(7,5)
ser

0     2
1     2
2     4
3     5
4     9
5     5
6     8
7     5
8     1
9     6
10    8
11    4
12    7
13    7
14    2
15    5
16    9
17    5
18    2
19    9
20    1
21    8
22    6
23    7
24    1
25    6
26    6
27    1
28    3
29    4
30    8
31    9
32    2
33    1
34    4
dtype: int64

19) ¿Obtener los valores de una serie conociendo la posicion por indice?

In [76]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
# a e i o u



20) ¿Como anadir series vertical u horizontalmente a un DataFrame?

In [110]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
df_ser1 = pd.DataFrame(ser1)
df_ser2 = pd.DataFrame(ser2)

df_vertical = pd.concat([df_ser1, df_ser2], axis=0)
df_vertical

df_horizontal = pd.concat([df_ser1, df_ser2], axis=1)
df_horizontal


0  0
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

22)¿Como importar solo columnas especificas de un archivo csv?
